// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package api

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2a0cac0DecodeGithubComOsspkgFdnsAppApi(in *jlexer.Lexer, out *AdblockListModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(AdblockListModel, 0, 1)
			} else {
				*out = AdblockListModel{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 AdblockListItemModel
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2a0cac0EncodeGithubComOsspkgFdnsAppApi(out *jwriter.Writer, in AdblockListModel) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v AdblockListModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2a0cac0EncodeGithubComOsspkgFdnsAppApi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdblockListModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2a0cac0EncodeGithubComOsspkgFdnsAppApi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdblockListModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2a0cac0DecodeGithubComOsspkgFdnsAppApi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdblockListModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2a0cac0DecodeGithubComOsspkgFdnsAppApi(l, v)
}
func easyjsonD2a0cac0DecodeGithubComOsspkgFdnsAppApi1(in *jlexer.Lexer, out *AdblockListItemModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int64(in.Int64())
		case "data":
			out.Data = string(in.String())
		case "count":
			out.Count = int64(in.Int64())
		case "deleted_at":
			if in.IsNull() {
				in.Skip()
				out.DeletedAt = nil
			} else {
				if out.DeletedAt == nil {
					out.DeletedAt = new(string)
				}
				*out.DeletedAt = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2a0cac0EncodeGithubComOsspkgFdnsAppApi1(out *jwriter.Writer, in AdblockListItemModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.String(string(in.Data))
	}
	{
		const prefix string = ",\"count\":"
		out.RawString(prefix)
		out.Int64(int64(in.Count))
	}
	{
		const prefix string = ",\"deleted_at\":"
		out.RawString(prefix)
		if in.DeletedAt == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.DeletedAt))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdblockListItemModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2a0cac0EncodeGithubComOsspkgFdnsAppApi1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdblockListItemModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2a0cac0EncodeGithubComOsspkgFdnsAppApi1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdblockListItemModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2a0cac0DecodeGithubComOsspkgFdnsAppApi1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdblockListItemModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2a0cac0DecodeGithubComOsspkgFdnsAppApi1(l, v)
}
