// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package api

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson168ae10cDecodeGithubComDewepOnlineFdnsInternalApi(in *jlexer.Lexer, out *CacheListItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "domain":
			out.Domain = string(in.String())
		case "ip":
			if in.IsNull() {
				in.Skip()
				out.IP = nil
			} else {
				in.Delim('[')
				if out.IP == nil {
					if !in.IsDelim(']') {
						out.IP = make([]string, 0, 4)
					} else {
						out.IP = []string{}
					}
				} else {
					out.IP = (out.IP)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.IP = append(out.IP, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson168ae10cEncodeGithubComDewepOnlineFdnsInternalApi(out *jwriter.Writer, in CacheListItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"domain\":"
		out.RawString(prefix[1:])
		out.String(string(in.Domain))
	}
	{
		const prefix string = ",\"ip\":"
		out.RawString(prefix)
		if in.IP == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.IP {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CacheListItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson168ae10cEncodeGithubComDewepOnlineFdnsInternalApi(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CacheListItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson168ae10cEncodeGithubComDewepOnlineFdnsInternalApi(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CacheListItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson168ae10cDecodeGithubComDewepOnlineFdnsInternalApi(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CacheListItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson168ae10cDecodeGithubComDewepOnlineFdnsInternalApi(l, v)
}
func easyjson168ae10cDecodeGithubComDewepOnlineFdnsInternalApi1(in *jlexer.Lexer, out *CacheList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(CacheList, 0, 1)
			} else {
				*out = CacheList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v4 CacheListItem
			(v4).UnmarshalEasyJSON(in)
			*out = append(*out, v4)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson168ae10cEncodeGithubComDewepOnlineFdnsInternalApi1(out *jwriter.Writer, in CacheList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v5, v6 := range in {
			if v5 > 0 {
				out.RawByte(',')
			}
			(v6).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v CacheList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson168ae10cEncodeGithubComDewepOnlineFdnsInternalApi1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CacheList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson168ae10cEncodeGithubComDewepOnlineFdnsInternalApi1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CacheList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson168ae10cDecodeGithubComDewepOnlineFdnsInternalApi1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CacheList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson168ae10cDecodeGithubComDewepOnlineFdnsInternalApi1(l, v)
}
