// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package webserver

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver(in *jlexer.Lexer, out *FixedListItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "types":
			out.Types = string(in.String())
		case "origin":
			out.Origin = string(in.String())
		case "domain":
			out.Domain = string(in.String())
		case "ips":
			out.IPs = string(in.String())
		case "active":
			out.Active = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver(out *jwriter.Writer, in FixedListItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"types\":"
		out.RawString(prefix[1:])
		out.String(string(in.Types))
	}
	{
		const prefix string = ",\"origin\":"
		out.RawString(prefix)
		out.String(string(in.Origin))
	}
	{
		const prefix string = ",\"domain\":"
		out.RawString(prefix)
		out.String(string(in.Domain))
	}
	{
		const prefix string = ",\"ips\":"
		out.RawString(prefix)
		out.String(string(in.IPs))
	}
	{
		const prefix string = ",\"active\":"
		out.RawString(prefix)
		out.Bool(bool(in.Active))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FixedListItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FixedListItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FixedListItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FixedListItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver(l, v)
}
func easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver1(in *jlexer.Lexer, out *FixedList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(FixedList, 0, 0)
			} else {
				*out = FixedList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 FixedListItem
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver1(out *jwriter.Writer, in FixedList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v FixedList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FixedList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FixedList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FixedList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver1(l, v)
}
func easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver2(in *jlexer.Lexer, out *CacheListItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "domain":
			out.Domain = string(in.String())
		case "ip":
			if in.IsNull() {
				in.Skip()
				out.IP = nil
			} else {
				in.Delim('[')
				if out.IP == nil {
					if !in.IsDelim(']') {
						out.IP = make([]string, 0, 4)
					} else {
						out.IP = []string{}
					}
				} else {
					out.IP = (out.IP)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					v4 = string(in.String())
					out.IP = append(out.IP, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "ttl":
			out.TTL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver2(out *jwriter.Writer, in CacheListItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"domain\":"
		out.RawString(prefix[1:])
		out.String(string(in.Domain))
	}
	{
		const prefix string = ",\"ip\":"
		out.RawString(prefix)
		if in.IP == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.IP {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"ttl\":"
		out.RawString(prefix)
		out.String(string(in.TTL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CacheListItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CacheListItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CacheListItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CacheListItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver2(l, v)
}
func easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver3(in *jlexer.Lexer, out *CacheList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(CacheList, 0, 1)
			} else {
				*out = CacheList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v7 CacheListItem
			(v7).UnmarshalEasyJSON(in)
			*out = append(*out, v7)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver3(out *jwriter.Writer, in CacheList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v8, v9 := range in {
			if v8 > 0 {
				out.RawByte(',')
			}
			(v9).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v CacheList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CacheList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CacheList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CacheList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver3(l, v)
}
func easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver4(in *jlexer.Lexer, out *BlockDomainModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "domain":
			out.Domain = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver4(out *jwriter.Writer, in BlockDomainModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"domain\":"
		out.RawString(prefix[1:])
		out.String(string(in.Domain))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BlockDomainModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BlockDomainModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BlockDomainModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BlockDomainModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver4(l, v)
}
func easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver5(in *jlexer.Lexer, out *AdblockURIModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "tag":
			out.Tag = string(in.String())
		case "uri":
			out.URI = string(in.String())
		case "active":
			out.Active = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver5(out *jwriter.Writer, in AdblockURIModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"tag\":"
		out.RawString(prefix[1:])
		out.String(string(in.Tag))
	}
	{
		const prefix string = ",\"uri\":"
		out.RawString(prefix)
		out.String(string(in.URI))
	}
	{
		const prefix string = ",\"active\":"
		out.RawString(prefix)
		out.Bool(bool(in.Active))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdblockURIModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdblockURIModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdblockURIModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdblockURIModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver5(l, v)
}
func easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver6(in *jlexer.Lexer, out *AdblockDomainModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "tag":
			out.Tag = string(in.String())
		case "domain":
			out.Domain = string(in.String())
		case "active":
			out.Active = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver6(out *jwriter.Writer, in AdblockDomainModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"tag\":"
		out.RawString(prefix[1:])
		out.String(string(in.Tag))
	}
	{
		const prefix string = ",\"domain\":"
		out.RawString(prefix)
		out.String(string(in.Domain))
	}
	{
		const prefix string = ",\"active\":"
		out.RawString(prefix)
		out.Bool(bool(in.Active))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdblockDomainModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdblockDomainModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdblockDomainModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdblockDomainModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver6(l, v)
}
func easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver7(in *jlexer.Lexer, out *AdblockActiveModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "domain":
			out.Domain = string(in.String())
		case "active":
			out.Active = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver7(out *jwriter.Writer, in AdblockActiveModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"domain\":"
		out.RawString(prefix[1:])
		out.String(string(in.Domain))
	}
	{
		const prefix string = ",\"active\":"
		out.RawString(prefix)
		out.Bool(bool(in.Active))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdblockActiveModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdblockActiveModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2a2898efEncodeGithubComDewepOnlineFdnsInternalWebserver7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdblockActiveModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdblockActiveModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2a2898efDecodeGithubComDewepOnlineFdnsInternalWebserver7(l, v)
}
